# Generated by Django 3.1.2 on 2020-11-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='salay',
            new_name='salary',
        ),
    ]
